**只打印或显示numpy数组rand_arr的小数点后3位。**

- `rand_arr = np.random.random([5, 3])`

【知识点：输入和输出】
- 如何在numpy数组中只打印小数点后三位？

In [1]:
import numpy as np

rand_arr = np.random.random([5, 3])
print(rand_arr)
# [[0.33033427 0.05538836 0.05947305]
#  [0.36199439 0.48844555 0.26309599]
#  [0.05361816 0.71539075 0.60645637]
#  [0.95000384 0.31424729 0.41032467]
#  [0.36082793 0.50101268 0.6306832 ]]

np.set_printoptions(precision=3)
print(rand_arr)
# [[0.33  0.055 0.059]
#  [0.362 0.488 0.263]
#  [0.054 0.715 0.606]
#  [0.95  0.314 0.41 ]
#  [0.361 0.501 0.631]]

[[0.03919232 0.10557733 0.59272316]
 [0.11233758 0.86621507 0.80156259]
 [0.39246188 0.28627015 0.39512703]
 [0.66165505 0.08903309 0.57863504]
 [0.75348456 0.27910769 0.20869666]]
[[0.039 0.106 0.593]
 [0.112 0.866 0.802]
 [0.392 0.286 0.395]
 [0.662 0.089 0.579]
 [0.753 0.279 0.209]]


**将numpy数组a中打印的项数限制为最多6个元素。**

【知识点：输入和输出】
- 如何限制numpy数组输出中打印的项目数？

In [4]:
import numpy as np

a = np.arange(15)
print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
np.set_printoptions(threshold=6)
print(a)
# [ 0  1  2 ... 12 13 14]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2 ... 12 13 14]


**打印完整的numpy数组a而不中断。**

【知识点：输入和输出】
- 如何打印完整的numpy数组而不中断？

In [6]:
import numpy as np

a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)
# [ 0  1  2 ... 12 13 14]
np.set_printoptions(threshold=np.iinfo(np.int).max)
print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
