In [11]:
rand_arr = np.random.random([5, 3])

In [2]:
import numpy as np

In [3]:
rand_arr = np.random.random([5, 3])

In [4]:
print(rand_arr)

[[0.84321644 0.48333508 0.61597542]
 [0.13023963 0.8492898  0.80441953]
 [0.20994028 0.71286509 0.35353822]
 [0.23971939 0.31690557 0.60333913]
 [0.92783125 0.0960922  0.68185974]]


In [8]:
np.set_printoptions(precision=3)

In [10]:
将numpy数组a中打印的项数限制为最多6个元素。

【知识点：输入和输出】

如何限制numpy数组输出中打印的项目数？



AttributeError: 'numpy.ndarray' object has no attribute 'files'

In [13]:
print(rand_arr)

[[0.948 0.812 0.662]
 [0.661 0.869 0.658]
 [0.803 0.096 0.251]
 [0.775 0.946 0.858]
 [0.622 0.856 0.627]]


In [14]:
import numpy as np

a = np.arange(15)
print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
np.set_printoptions(threshold=6)
print(a)
# [ 0  1  2 ... 12 13 14]

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 0  1  2 ... 12 13 14]


In [15]:
import numpy as np

a = np.arange(15)
np.set_printoptions(threshold=6)
print(a)
# [ 0  1  2 ... 12 13 14]
np.set_printoptions(threshold=np.iinfo(np.int).max)
print(a)
# [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 0  1  2 ... 12 13 14]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
